import { jest, describe, test, expect, beforeEach } from '@jest/globals';
import YAML from 'yaml';

// Mock fs module
jest.unstable_mockModule('fs', () => ({
  default: {
    existsSync: jest.fn(),
    readFileSync: jest.fn(),
    writeFileSync: jest.fn(),
    mkdirSync: jest.fn(),
    rmSync: jest.fn()
  },
  existsSync: jest.fn(),
  readFileSync: jest.fn(),
  writeFileSync: jest.fn(),
  mkdirSync: jest.fn(),
  rmSync: jest.fn()
}));

// Mock uuid
jest.unstable_mockModule('uuid', () => ({
  v4: jest.fn(() => 'test-uuid-' + Math.random().toString(36).substr(2, 9))
}));

// Import after mocking
const fsMock = await import('fs');
const { parseVariablesFromFile, detectConflicts, executeImport } = await import('../src/core/import.js');

// Helper to set up store with variables
function setupStore(vars = []) {
  const storeData = {
    version: 2,
    encryption: 'none',
    vars,
    targets: {}
  };
  fsMock.default.existsSync.mockReturnValue(true);
  fsMock.default.readFileSync.mockReturnValue(YAML.stringify(storeData));
}

describe('Import Module', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('parseVariablesFromFile', () => {
    test('parses dotenv format (KEY=value)', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        'API_KEY=secret123\nDB_HOST=localhost\nDB_PORT=5432\n'
      );

      const result = parseVariablesFromFile('/path/to/.env');
      expect(result.type).toBe('dotenv');
      expect(result.error).toBeUndefined();
      expect(result.vars).toEqual({
        API_KEY: 'secret123',
        DB_HOST: 'localhost',
        DB_PORT: '5432'
      });
    });

    test('parses dotenv format with quoted values', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        'API_KEY="secret123"\nDB_HOST=\'localhost\'\n'
      );

      const result = parseVariablesFromFile('/path/to/.env');
      expect(result.vars.API_KEY).toBe('secret123');
      expect(result.vars.DB_HOST).toBe('localhost');
    });

    test('parses shell format (export KEY="value")', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        'export API_KEY="secret123"\nexport DB_HOST="localhost"\n'
      );

      const result = parseVariablesFromFile('/path/to/.zshrc');
      expect(result.type).toBe('shell');
      expect(result.vars).toEqual({
        API_KEY: 'secret123',
        DB_HOST: 'localhost'
      });
    });

    test('skips comments and blank lines', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        '# This is a comment\n\nAPI_KEY=value1\n# Another comment\nDB_HOST=value2\n\n'
      );

      const result = parseVariablesFromFile('/path/to/.env');
      expect(Object.keys(result.vars)).toHaveLength(2);
      expect(result.vars.API_KEY).toBe('value1');
      expect(result.vars.DB_HOST).toBe('value2');
    });

    test('returns error for nonexistent file', () => {
      fsMock.default.existsSync.mockReturnValue(false);
      fsMock.default.readFileSync.mockReturnValue(null);

      const result = parseVariablesFromFile('/path/to/nonexistent.env');
      expect(result.error).toBeDefined();
      expect(Object.keys(result.vars)).toHaveLength(0);
    });

    test('returns empty vars for file with no valid entries', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        '# Only comments\n# Nothing to parse\n\n'
      );

      const result = parseVariablesFromFile('/path/to/.env');
      expect(Object.keys(result.vars)).toHaveLength(0);
      expect(result.error).toBeUndefined();
    });

    test('handles shell file with mixed content', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        '#!/bin/bash\n# Config\nexport PATH="/usr/local/bin:$PATH"\nexport API_KEY="mykey"\necho "hello"\n'
      );

      const result = parseVariablesFromFile('/path/to/config.sh');
      expect(result.type).toBe('shell');
      // Should pick up export lines, skip non-export lines
      expect(result.vars.API_KEY).toBe('mykey');
    });

    test('handles file with evk managed block content', () => {
      fsMock.default.existsSync.mockReturnValue(true);
      fsMock.default.readFileSync.mockReturnValue(
        'EXISTING_VAR=old\n# === evk Managed Block ===\n# Auto-generated by evk.\nMANAGED_VAR=managed\n# === End evk Managed Block ===\n'
      );

      const result = parseVariablesFromFile('/path/to/.env');
      // Should import all variables including managed ones
      expect(result.vars.EXISTING_VAR).toBe('old');
      expect(result.vars.MANAGED_VAR).toBe('managed');
    });
  });

  describe('detectConflicts', () => {
    test('detects no conflicts for empty store', () => {
      setupStore([]);

      const { toImport, conflicts, unchanged } = detectConflicts({ API_KEY: 'value1', DB_HOST: 'value2' }, []);
      expect(toImport).toHaveLength(2);
      expect(conflicts).toHaveLength(0);
      expect(unchanged).toHaveLength(0);
    });

    test('detects conflicts for existing keys with different values', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'existing', tags: [], description: '', created_at: '', updated_at: '' }
      ]);

      const { toImport, conflicts, unchanged } = detectConflicts({ API_KEY: 'new-value', DB_HOST: 'value2' }, []);
      expect(toImport).toHaveLength(1);
      expect(toImport[0].key).toBe('DB_HOST');
      expect(conflicts).toHaveLength(1);
      expect(conflicts[0].key).toBe('API_KEY');
      expect(conflicts[0].existing.value).toBe('existing');
      expect(unchanged).toHaveLength(0);
    });

    test('treats same value as unchanged (not conflict)', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'same-value', tags: [], description: '', created_at: '', updated_at: '' }
      ]);

      const { toImport, conflicts, unchanged } = detectConflicts({ API_KEY: 'same-value', DB_HOST: 'new' }, []);
      expect(toImport).toHaveLength(1);
      expect(toImport[0].key).toBe('DB_HOST');
      expect(conflicts).toHaveLength(0);
      expect(unchanged).toHaveLength(1);
      expect(unchanged[0].key).toBe('API_KEY');
    });

    test('detects conflicts with matching tags', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'dev-value', tags: ['dev'], description: '', created_at: '', updated_at: '' }
      ]);

      const { toImport, conflicts } = detectConflicts({ API_KEY: 'new-value' }, ['dev']);
      expect(conflicts).toHaveLength(1);
      expect(conflicts[0].key).toBe('API_KEY');
    });

    test('treats same value with tags as unchanged', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'dev-value', tags: ['dev'], description: '', created_at: '', updated_at: '' }
      ]);

      const { conflicts, unchanged } = detectConflicts({ API_KEY: 'dev-value' }, ['dev']);
      expect(conflicts).toHaveLength(0);
      expect(unchanged).toHaveLength(1);
    });

    test('no conflict when tags differ', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'dev-value', tags: ['dev'], description: '', created_at: '', updated_at: '' }
      ]);

      const { toImport, conflicts } = detectConflicts({ API_KEY: 'prod-value' }, ['prod']);
      expect(toImport).toHaveLength(1);
      expect(conflicts).toHaveLength(0);
    });

    test('no conflict when importing without tags and store has tagged entry', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'dev-value', tags: ['dev'], description: '', created_at: '', updated_at: '' }
      ]);

      const { toImport, conflicts, unchanged } = detectConflicts({ API_KEY: 'new-value' }, []);
      expect(toImport).toHaveLength(1);
      expect(toImport[0].key).toBe('API_KEY');
      expect(conflicts).toHaveLength(0);
      expect(unchanged).toHaveLength(0);
    });

    test('conflict only when exact key+tags match', () => {
      setupStore([
        { id: 'id-1', key: 'API_KEY', value: 'no-tag-value', tags: [], description: '', created_at: '', updated_at: '' },
        { id: 'id-2', key: 'API_KEY', value: 'dev-value', tags: ['dev'], description: '', created_at: '', updated_at: '' }
      ]);

      // Importing without tags should conflict with the no-tag entry only
      const { toImport, conflicts } = detectConflicts({ API_KEY: 'new-value' }, []);
      expect(conflicts).toHaveLength(1);
      expect(conflicts[0].existing.value).toBe('no-tag-value');
      expect(toImport).toHaveLength(0);
    });
  });

  describe('executeImport', () => {
    test('imports variables into store', () => {
      setupStore([]);

      const variables = [
        { key: 'VAR1', value: 'value1' },
        { key: 'VAR2', value: 'value2' }
      ];

      const result = executeImport(variables, { tags: ['test'] });
      expect(result.imported).toBe(2);
      // Verify writeStore was called (addVariable calls writeStore)
      expect(fsMock.default.writeFileSync).toHaveBeenCalled();
    });

    test('imports with empty tags', () => {
      setupStore([]);

      const variables = [{ key: 'VAR1', value: 'value1' }];
      const result = executeImport(variables, {});
      expect(result.imported).toBe(1);
    });

    test('returns zero for empty variables list', () => {
      setupStore([]);

      const result = executeImport([], { tags: [] });
      expect(result.imported).toBe(0);
    });
  });
});
