/**
 * Detect target file type based on path
 * @param {string} filePath - Path to target file
 * @returns {'shell'|'dotenv'} File type
 */
export function detectTargetType(filePath) {
  if (filePath.endsWith('.env') || filePath.includes('.env.')) {
    return 'dotenv';
  }
  if (filePath.includes('rc') || filePath.endsWith('.sh') ||
      filePath.endsWith('.bash') || filePath.endsWith('.zsh')) {
    return 'shell';
  }
  return 'shell'; // default
}

/**
 * Block markers
 */
export const BLOCK_START = '# === evk Managed Block ===';
export const BLOCK_END = '# === End evk Managed Block ===';
export const DEPRECATED_MARKER = '# --- Deprecated on';

/**
 * Extract managed block from file content
 * @param {string} content - File content
 * @returns {object|null} Block info or null
 */
export function extractManagedBlock(content) {
  const startIdx = content.indexOf(BLOCK_START);
  const endIdx = content.indexOf(BLOCK_END);

  if (startIdx === -1 || endIdx === -1) {
    return null;
  }

  const blockContent = content.slice(startIdx, endIdx + BLOCK_END.length);
  return {
    start: startIdx,
    end: endIdx + BLOCK_END.length,
    content: blockContent,
    raw: blockContent
  };
}

/**
 * Parse variables from a managed block
 * @param {string} blockContent - Block content
 * @param {'shell'|'dotenv'} type - File type
 * @returns {object} Parsed variables {key: value}
 */
export function parseVarsFromBlock(blockContent, type) {
  const vars = {};
  const lines = blockContent.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    let match;
    if (type === 'shell') {
      // export KEY="value" or export KEY='value' or export KEY=value
      match = trimmed.match(/^export\s+([A-Za-z_][A-Za-z0-9_]*)=["']?(.*)["']?$/);
    } else {
      // KEY=value or KEY="value"
      match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=["']?(.*)["']?$/);
    }

    if (match) {
      const [, key, value] = match;
      // Remove trailing quote if present
      vars[key] = value.replace(/["']$/, '');
    }
  }

  return vars;
}

/**
 * Format timestamp for block header
 * @returns {string} Formatted timestamp
 */
export function formatTimestamp() {
  const now = new Date();
  return now.toISOString().replace('T', ' ').slice(0, 19);
}

/**
 * Generate a managed block
 * @param {object} newVars - Variables to include {key: {value, ...}}
 * @param {object} oldVars - Old variables for deprecation {key: value}
 * @param {'shell'|'dotenv'} type - Target type
 * @returns {string} Generated block
 */
export function generateBlock(newVars, oldVars, type) {
  const timestamp = formatTimestamp();
  const lines = [
    BLOCK_START,
    '# Auto-generated by evk. Do not edit manually.',
    `# Last updated: ${timestamp}`,
    ''
  ];

  // Add active variables
  for (const [key, data] of Object.entries(newVars)) {
    const value = typeof data === 'object' ? data.value : data;
    if (type === 'shell') {
      lines.push(`export ${key}="${value}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }

  // Add deprecated variables
  const deprecated = [];
  for (const [key, value] of Object.entries(oldVars)) {
    if (!newVars[key]) {
      if (type === 'shell') {
        deprecated.push(`# export ${key}="${value}"`);
      } else {
        deprecated.push(`# ${key}=${value}`);
      }
    }
  }

  if (deprecated.length > 0) {
    lines.push('');
    lines.push(`${DEPRECATED_MARKER} ${timestamp} ---`);
    lines.push(...deprecated);
  }

  lines.push(BLOCK_END);

  return lines.join('\n');
}
